
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "power-position-service.fullname" . }}
  labels:
    {{- include "power-position-service.labels" . | nindent 4 }}
data:
  intervalMinutes: {{ default "1" .Values.powerPositionSettings.intervalMinutes | quote }}
  timeZoneId: {{ default "Europe/London" .Values.powerPositionSettings.timeZoneId | quote }}
  retryAttempts: {{ default "3" .Values.powerPositionSettings.retryAttempts | quote }}
  retryDelaySeconds: {{ default "10" .Values.powerPositionSettings.retryDelaySeconds | quote }}
  maxDlqRetryAttempts: {{ default "5" .Values.powerPositionSettings.maxDlqRetryAttempts | quote }}
  loggingLevel: {{ default "Information" .Values.logging.level | quote }}
