
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "power-position-service.fullname" . }}
  labels:
    {{- include "power-position-service.labels" . | nindent 4 }}
type: Opaque
data:
  powerServiceApiKey: {{ default "" .Values.secrets.powerServiceApiKey | b64enc | quote }}
  {{- with .Values.secrets }}
  {{- if .powerServiceUsername }}
  powerServiceUsername: {{ .powerServiceUsername | b64enc | quote }}
  {{- end }}
  {{- if .powerServicePassword }}
  powerServicePassword: {{ .powerServicePassword | b64enc | quote }}
  {{- end }}
  {{- end }}
